---
# https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md

- name: Ensure Python3 is installed
  ansible.builtin.package:
    name: 
    # - python3
    # - python3-distutils
      - pipx
    state: present
  become: yes

- name: Install Poetry using pipx
  ansible.builtin.command:
    cmd: pipx install poetry
    creates: ~/.local/bin/poetry

- name: Clone git repository
  ansible.builtin.git:
    repo: "{{ lnbits_repository_url }}"
    dest: "{{ lnbits_root_path }}"
    version: "{{ lnbits_version }}"
    force: true
  register: git_repository
  when: not blee_devmode

- name: Install all lnbits dependencies using Poetry
  ansible.builtin.command:
    cmd: ~/.local/bin/poetry install --only main
    chdir: "{{ lnbits_root_path }}"
  when: git_repository.changed or blee_devmode

- name: Append poetry completions to .bash_completion
  ansible.builtin.lineinfile:
    path: ~/.bash_completion
    line: poetry completions bash
    create: yes

- name: Create a configuration file from the sample
  ansible.builtin.copy:
    src: "{{ lnbits_root_path }}/.env.example"
    dest: "{{ lnbits_root_path }}/.env"
    mode: 0640
    force: no
    remote_src: yes
  when: not blee_devmode