---
- name: Ensure root path
  ansible.builtin.file:
    path:  "{{ lnbits_root_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Set up a the lnbits group
  ansible.builtin.group:
    name: "{{ lnbits_system_group }}"
    state: present
  when: lnbits_system_group is defined

- name: "Add {{ ansible_user }} to the lnbits group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ lnbits_system_group }}"
    append: yes
  when: lnbits_system_group is defined