---
- name: Ensure root path
  ansible.builtin.file:
    path:  "{{ lnbits_root_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
